---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sock-shop-chaos-engine
  namespace: sock-shop
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sock-shop-chaos-engine
  namespace: sock-shop
rules:
- apiGroups: ["","apps","batch","extensions","litmuschaos.io","openebs.io","storage.k8s.io"]
  resources: ["chaosengines","chaosexperiments","chaosresults","cstorpools","cstorvolumereplicas","configmaps","secrets","pods","pods/exec","pods/log","pods/eviction","jobs","replicasets","deployments","daemonsets","statefulsets","persistentvolumeclaims","persistentvolumes","storageclasses","services","events"]
  verbs: ["create","delete","get","list","patch","update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get","list","patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sock-shop-chaos-engine
  namespace: sock-shop
roleRef:
  kind: ClusterRole
  name: sock-shop-chaos-engine
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: sock-shop-chaos-engine
  namespace: sock-shop
