dist: trusty
install: true
language: go
go:
  - 1.11.2
env:
  global:
    - GOARCH=amd64
addons:
  sonarcloud:
    organization: "litmuschaos"
    token:
      secure: "qcwKL1Hetr6zzPffAuTbKCmWv9h+bfA8DliXNXocO8Gv2Xgaa4G1vt7T/vWGCii9gM86/Ki0N6QerC3M/EiQguGZiq01Waun1nyg+/6Ix1N+53pvb3YS0YGNNOjBYyYT8zUiDnHskpU7ajfAJu/bF3i/NOL6ylX5txdqFphI3CJHL3R857GsG9kqSjbXa1iMg2lEsYiLPii1Vjf3lQAoPaK9nd10TK1kL7+vtZxIbSuMllbLRHcuFFZpi7MzMO25Tm2u5cO37CVdDJ5TE0wT4hcJ5gkDcOP1rZ+zHrUaqNZCccT30H9Ob7h+kwV+VynG7TVNP2sMHv3NJlCz50U2gkqdAEMdX7wpIOPNx+qH3bi/n64Podl64WXlvjgS8I6X8Iqd6Q9fwGrofFuC2sPSOwgdadG+E0s6FWJ5L9DAoSNLct02pxYvmLsIZ2W55RLaxPYhi8P1rIroZd+bYhJVqO5Sk2D695w6kBdpWkP89pfG8yGVFGNpdGiTdVOmIYD1KjZlY7PrpWbkUZGiE+XSAkqtTExViTTGZenmqkidb8yTrNQXtyxKgy567Wzi80QQfcAqSuFRQMW1tkw6VaydweLof0Ie92AO2vVTARnVHZtDubLr7mIXpRxmx2oj5XdSU8RdeKBgKehhcrVc9dId2VPQkfXokoLVNm8aurOFYFs=" # encrypted value of your token

before_install:
  - sleep 15
  - sudo apt-get install -y
  - sudo apt-get install -y curl
script:
  - make
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then sonar-scanner; fi

