---
# Source: openebs/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: app-namespace
  labels:
    name: app-namespace
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-namespace
  namespace: app-namespace
  labels:
    name: app-namespace

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: app-namespace
  labels:
    name: app-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-namespace
subjects:
- kind: ServiceAccount
  name: app-namespace
  namespace: app-namespace

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: prometheus-liveness-
  namespace: app-namespace
spec:
  template:
    metadata:
      name: prometheus-liveness
      namespace: app-namespace
      labels:
        liveness: prometheus-liveness
    spec:
      serviceAccountName: app-namespace
      restartPolicy: Never
      containers:
      - name: prometheus-liveness  
        image : openebs/service-liveness
        imagePullPolicy: Always
        env:

          - name: LIVENESS_TIMEOUT_SECONDS
            value: "liveness-timeout-seconds"

          # number of retries when livenss-fails 
          - name: LIVENESS_RETRY_COUNT
            value: "liveness-retry-count"

          - name: LIVENESS_PERIOD_SECONDS
            value: "liveness-period-seconds"

          - name: SERVICE_ENDPOINT
            value: "service-endpoint"

          - name: PORT
            value: "port"
          
            # Namespace in which prometheus is running
          - name: APP_NAMESPACE
            value: "app-namespace"

        
