# TODO 
# Delete storage pool and storage class

- hosts: localhost
  connection: local

  vars_files:
  - vars.yaml

  tasks:
    - block:
          - block:
            ## RECORD START of litmus job
            - name: Record test instance/run ID
              set_fact:
                run_id: "{{ lookup('env','RUN_ID') }}"
            - name: Construct testname appended with runID
              set_fact:
                test_name: "{{ cleanup_test_name }}-{{ run_id }}"
            when: lookup('env','RUN_ID')

          - name: Generate the litmus result CR to reflect Start of Cleanup
            template:
              src: /litmus-result.j2
              dest: litmus-result.yaml
            vars:
              test: "{{ cleanup_test_name }}"
              chaostype: ""
              app: ""
              phase: in-progress
              verdict: none
          
          - name: Analyze the cr yaml
            shell: cat litmus-result.yaml

          - name: Apply the litmus result CR
            shell: kubectl apply -f litmus-result.yaml
            args:
              executable: /bin/bash
            register: lr_status 
            failed_when: "lr_status.rc != 0"

          - block:
              - template:
                  src: storageclass-jiva.j2
                  dest: "{{ storage_class_jiva }}"

              - name: Deleting storage class
                shell: "{{ kubeapply }} delete -f {{ storage_class_jiva }}" 
                args:
                  executable: /bin/bash
                ignore_errors: True

              - name: Confirm that openebs storage pools are deleted
                shell: kubectl get storagepool
                args:
                  executable: /bin/bash
                register: result_sp
                until: "lookup('env','JIVA_POOL_NAME') not in result_sp.stdout"
                delay: 10
                retries: 300

              - name: Confirm that openebs storage classes are deleted
                shell: kubectl get storageclass
                args:
                  executable: /bin/bash
                register: result_sc
                until: "lookup('env','JIVA_STORAGECLASS_NAME') not in result_sc.stdout"
                delay: 10
                retries: 300
            when: lookup('env','DELETE_JIVA') == "true"

          - block:
              - template:
                  src: storageclass-cstor.j2
                  dest: "{{ storage_class_cstor }}"

              - name: Add the disks to the pool
                lineinfile:
                  path: "{{ storage_class_cstor }}"
                  insertafter: 'diskList:'
                  line: '     - {{ item }}'
                with_items: "{{ lookup('env','DISK_LIST').split(\",\") }}"

              - name: Deleting storage class
                shell: "{{ kubeapply }} delete -f {{ storage_class_cstor }}" 
                args:
                  executable: /bin/bash
                ignore_errors: True

              - name: Confirm that openebs storage pools are deleted
                shell: kubectl get storagepool
                args:
                  executable: /bin/bash
                register: result_sp
                until: "lookup('env','CSTOR_POOL_NAME') not in result_sp.stdout"
                delay: 10
                retries: 300

              - name: Confirm that openebs storage classes are deleted
                shell: kubectl get storageclass
                args:
                  executable: /bin/bash
                register: result_sc
                until: "lookup('env','CSTOR_STORAGECLASS_NAME') not in result_sc.stdout"
                delay: 10
                retries: 300 
            when: lookup('env','DELETE_CSTOR') == "true"

          - set_fact:
              flag: "Pass"
      rescue: 
        - set_fact: 
            flag: "Fail"

      always:
        ## Updating status to CR
        - name: Generate the litmus result CR to reflect End Of Cleanup
          template:
            src: /litmus-result.j2
            dest: litmus-result.yaml
          vars:
            test: "{{ cleanup_test_name }}"
            chaostype: ""
            app: ""
            phase: completed
            verdict: "{{ flag }}"

        - name: Analyze the cr yaml
          shell: cat litmus-result.yaml
          

        - name: Apply the litmus result CR
          shell: kubectl apply -f litmus-result.yaml
          args:
            executable: /bin/bash
          register: lr_status
          failed_when: "lr_status.rc != 0"
