---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: #{AGENT-NAMESPACE}
data:
  config: |
    containerRuntimeExecutor: #{ARGO-CONTAINER-RUNTIME-EXECUTOR}
    executor:
      imagePullPolicy: Always
