---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: #{AGENT_NAMESPACE}
data:
  SERVER_ADDR: #{SERVER_ADDR}
  AGENT_SCOPE: #{AGENT_SCOPE}
  VERSION: #{VERSION}
  START_TIME: #{START_TIME}
  SKIP_SSL_VERIFY: "#{SKIP_SSL_VERIFY}"
  IS_CLUSTER_CONFIRMED: #{IS_CLUSTER_CONFIRMED}
  COMPONENTS: |
    DEPLOYMENTS: #{AGENT_DEPLOYMENTS}
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-secret
  namespace: #{AGENT_NAMESPACE}
stringData:
  CUSTOM_TLS_CERT: "#{CUSTOM_TLS_CERT}"
  CLUSTER_ID: #{CLUSTER_ID}
  ACCESS_KEY: #{ACCESS_KEY}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: #{AGENT_NAMESPACE}
  labels:
    app: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      serviceAccountName: #{SUBSCRIBER_SERVICE_ACCOUNT}
      #{TOLERATIONS}
      #{NODE_SELECTOR}
      containers:
        - name: subscriber
          image: #{SUBSCRIBER_IMAGE}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 2000
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: agent-config
            - secretRef:
                name: agent-secret
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "300Mi"
              cpu: "125m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "500Mi"
              cpu: "225m"
              ephemeral-storage: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-tracker
  name: event-tracker
  namespace: #{AGENT_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-tracker
  template:
    metadata:
      labels:
        app: event-tracker
    spec:
      serviceAccountName: event-tracker-sa
      #{TOLERATIONS}
      #{NODE_SELECTOR}
      containers:
        - image: #{EVENT_TRACKER_IMAGE}
          imagePullPolicy: Always
          name: litmus-event-tracker
          securityContext:
            runAsUser: 2000
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: agent-config
            - secretRef:
                name: agent-secret
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "300Mi"
              cpu: "125m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "500Mi"
              cpu: "225m"
              ephemeral-storage: "1Gi"
