---
- name: Get the liveness pods
  shell: kubectl get pod -n {{ liveness_namespace }} -l {{ liveness_label }} -o=custom-columns=NAME:".metadata.name" --no-headers
  register: liveness_pods

- name: Checking status of liveness pods
  shell: kubectl get pods {{ item }} -n {{ liveness_namespace }} -o=custom-columns=NAME:".status.phase" --no-headers
  register: result
  with_items: "{{ liveness_pods.stdout_lines }}"
  until: "'Running' in result.stdout"
  delay: 10
  retries: 10

