---
- name: Obtain list of existing namespaces
  shell: >
    kubectl get ns 
    --no-headers 
    -o custom-columns=:metadata.name
  args: 
    executable: /bin/bash
  register: ns_list

- name: Create test specific namespace.
  shell: kubectl create ns {{ app_ns }}
  args:
    executable: /bin/bash
  when: app_ns != 'litmus' and app_ns not in ns_list.stdout_lines

- include_tasks: /utils/k8s/status_testns.yml

