---
- block:
    - name: Check whether the provider storageclass is applied
      k8s_facts:
        kind: StorageClass
        name: "{{ lookup('env','PROVIDER_STORAGE_CLASS') }}"
      register: result

    - name: Replace the pvc placeholder with provider
      replace:
        path: "{{ application_deployment }}"
        regexp: "testclaim"
        replace: "{{ lookup('env','APP_PVC') }}"

    - name: Replace the storageclass placeholder with provider
      replace:
        path: "{{ application_deployment }}"
        regexp: "testclass"
        replace: "{{ lookup('env','PROVIDER_STORAGE_CLASS') }}"

    - include_tasks: /utils/scm/openebs/fetch_replica_values.yml
      when: lookup('env', 'APP_REPLICA')

    - name: Get the application label values from env
      set_fact:
         app_lkey: "{{ app_label.split('=')[0] }}"
         app_lvalue: "{{ app_label.split('=')[1] }}"

    - name: Replace the application label placeholder in deployment spec
      replace:
        path: "{{ application_deployment }}"
        regexp: "lkey: lvalue"
        replace: "{{ app_lkey }}: {{ app_lvalue }}"

    - name: Enable/Disable I/O based liveness probe 
      shell: >
        sed -i '/#<!-- BEGIN ANSIBLE MANAGED BLOCK -->/
        ,/#<!-- END ANSIBLE MANAGED BLOCK -->/d' 
        {{ application_deployment }}
      args:
        executable: /bin/bash
      when: lookup('env', 'IO_PROBE') is defined and lookup('env', 'IO_PROBE') == "disabled"

    - include_tasks: /utils/k8s/create_ns.yml
