---
  ## Execute this util to perform AWS instance chaos using chaostoolkit-aws
  ## chaos_file: pod-app-kill-count.j2,
  ## Requiered variables(region, access_key_id, secrete_access_key, chaos_action(stop_instances,stop_instances_any_type), aws_instance_id) 
  ## need to be passed or defined before populating json.
- name: Get the chaos util to perfom chaos test
  template:
    src: "/choslib/chaostoolkit/kubernetes/{{ chaos_file }}"
    dest: pod-app-kill-count.json

- name: Fetch the content of json file to start chaos on node
  command: cat pod-app-kill-count.json
  register: json_output
  failed_when: "json_output.rc != 0"

  ## Invoke this by passing attribute display with values as (true or false) to check the content of json
- debug:
    msg: "{{json_output.stdout}}"
  when: "{{display}} == 'true'"

- name: Create the pod which will perform acation on k8
  shell: kubectl apply -f {{ chaos_file }} -n {{ namespace }}
  args:
    executable: /bin/bash

