---
# This util checks the application status in k8s cluster
# The parameters required are
#     - app_ns ( namespace where the application is deployed)
#     - app_label ( Label of application in the form 'key=value'))

- block:
    - name: Check the pod status
      shell: >
        kubectl get pods -n {{ app_ns }} -l {{ app_label }} --no-headers
        -o custom-columns=:status.phase
      args:
        executable: /bin/bash
      register: result
      until: "'Running' in result.stdout"
      delay: 30
      retries: 15
      
  when: lookup('env','DEPLOY_TYPE') == 'deployment'

- block:
    - name: obtain the number of replicas.
      shell: kubectl get statefulset -n {{ app_ns }} -l {{ app_label }} -o custom-columns=:spec.replicas
      register: rep_count 
      until: "rep_count.rc ==0"
      delay: 60
      retries: 15

    - name: Obtain the ready replica count and compare with the replica count.
      shell: kubectl get statefulset -n {{ app_ns }} -l {{ app_label }} -o custom-columns=:..readyReplicas
      register: ready_rep
      until: "ready_rep.rc == 0 and ready_rep.stdout|int == rep_count.stdout|int"
      delay: 60
      retries: 30

  when: lookup('env','DEPLOY_TYPE') == 'statefulset'
