---
- hosts: localhost
  connection: local

  vars_files:
    - test_vars.yml

  tasks:
    - block:
        
         ## Generating the testname for deployment
        - include_tasks: /utils/fcm/create_testname.yml

         ## RECORD START-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
          vars:
            status: 'SOT'

        - block:
            - name: Get the application label values from env
              set_fact:
                 app_lkey: "{{ app_label.split('=')[0] }}"
                 app_lvalue: "{{ app_label.split('=')[1] }}"

            - name: Replace the application label placeholder in deployment spec
              replace:
                path: "{{ application_deployment }}"
                regexp: "lkey: lvalue"
                replace: "{{ app_lkey }}: {{ app_lvalue }}"

         ## Deploying the application
            - include_tasks: /utils/k8s/deploy_single_app.yml
              vars:
                check_app_pod: 'yes'
                delay: 10
                retries: 100

            - set_fact:
                flag: "Pass"

          when: "'deprovision' not in action"

        - block:

            - name: Deprovisioning the Application
              shell: kubectl delete -f {{ application_deployment }} -n {{ app_ns }}
      
            - name: Check if the application pod is deleted.
              shell: kubectl get pods -n {{ app_ns }} -l {{ app_label }} --no-headers -o custom-columns=:status.phase
              args:
                executable: /bin/bash
              register: result
              until: "'Running' not in result.stdout"
              delay: 5
              retries: 40

            - set_fact:
                flag: "Pass"

          when: "'deprovision' is in action"

      rescue:
        - set_fact:
            flag: "Fail"

      always:
            ## RECORD END-OF-TEST IN LITMUS RESULT CR
        - include_tasks: /utils/fcm/update_litmus_result_resource.yml
          vars:
            status: 'EOT'
