---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chaos-monitor
  name: chaos-monitor
  namespace: litmus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-monitor
  template:
    metadata:
      labels:
        app: chaos-monitor
    spec:
      containers:
      - image: litmuschaos/chaos-exporter:ci
        imagePullPolicy: Always
        name: chaos-exporter
      serviceAccount: litmus
      serviceAccountName: litmus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaos-monitor
  name: chaos-monitor
  namespace: litmus
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: chaos-monitor
  type: ClusterIP
