---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: #{AGENT-NAMESPACE}
data:
  SERVER_ADDR: #{SERVER_ADDR}
  CLUSTER_ID: #{CLUSTER_ID}
  ACCESS_KEY: #{ACCESS_KEY}
  AGENT_SCOPE: #{AGENT-SCOPE}
  VERSION: #{VERSION}
  START_TIME: #{START_TIME}
  SKIP_SSL_VERIFY: "#{SKIP_SSL_VERIFY}"
  CUSTOM_TLS_CERT: "#{CUSTOM_TLS_CERT}"
  IS_CLUSTER_CONFIRMED: #{IS_CLUSTER_CONFIRMED}
  COMPONENTS: |
    DEPLOYMENTS: #{AGENT-DEPLOYMENTS}
---
apiVersion: v1
kind: Secret
metadata:
  name: agent-secret
  namespace: #{AGENT-NAMESPACE}
stringData:
  CLUSTER_ID: #{CLUSTER_ID}
  ACCESS_KEY: #{ACCESS_KEY}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  namespace: #{AGENT-NAMESPACE}
  labels:
    app: subscriber
spec:
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      #{tolerations}
      #{nodeselector}
      serviceAccountName: #{SUBSCRIBER-SERVICE-ACCOUNT}
      containers:
        - name: subscriber
          image: #{SUBSCRIBER-IMAGE}
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
          imagePullPolicy: Always
          securityContext:
            runAsUser: 2000
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: agent-config
            - secretRef:
                name: agent-secret
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "300Mi"
              cpu: "125m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "500Mi"
              cpu: "225m"
              ephemeral-storage: "1Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: event-tracker
  name: event-tracker
  namespace: #{AGENT-NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-tracker
  template:
    metadata:
      labels:
        app: event-tracker
    spec:
      #{tolerations}
      #{nodeselector}
      serviceAccountName: event-tracker-sa
      containers:
        - image: #{EVENT-TRACKER-IMAGE}
          imagePullPolicy: Always
          securityContext:
            runAsUser: 2000
            allowPrivilegeEscalation: false
          name: litmus-event-tracker
          envFrom:
            - configMapRef:
                name: agent-config
          env:
            - name: AGENT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "300Mi"
              cpu: "125m"
              ephemeral-storage: "500Mi"
            limits:
              memory: "500Mi"
              cpu: "225m"
              ephemeral-storage: "1Gi"