base_url: https://api.packet.net # base url for access packet api
performance_tier: storage_1 # storage_1=Performance tier: Standard & storage_2 = Performance tier: Performance
location: ams1 # location available: ams1, ewr1, nrt1 & sjc1
billing_cycle: hourly
size: 50 # size in GB
device_id_location: /tmp/packet/device_id # file location where cluster device id stored
project_id: bdbd5cf0-7453-434b-99f8-0c3e3f83dbe2 # project id of packet cloud
mount_path: /var/openebs

# options: attach,format
disk_action: attach